### ISSUE TITLE
Jvm desktop not draw

### ISSUE THREAD

**Issue by toffeantyri** [alexzhirkevich/compottie#5] opened 2024-06-05 12:39 UTC
Android:  lottie animation drawing is success.

Jvm : not work. Empty screen( no animation, no image

```

Composable
actual fun LoadingCardGeneralView(
    modifier: Modifier,
    bottomElement: @Composable (() -> Unit)?
) {
    val animationBites = remember {
        mutableStateOf(ByteArray(0))
    }

    LaunchedEffect(Unit) {
        withContext(Dispatchers.IO) {
            animationBites.value = Res.readBytes("files/loading.json")
        }
    }

    val jsonString = remember(animationBites.value) {
        mutableStateOf(animationBites.value.decodeToString())
    }

    val composition by rememberLottieComposition(
        LottieCompositionSpec.JsonString(jsonString.value)
    )

    val progress = animateLottieCompositionAsState(
        composition = composition,
        iterations = LottieConstants.IterateForever
    )

    val painter = rememberLottiePainter(composition, progress.value)


    Column(modifier = modifier) {
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .ignoreHorizontalParentPadding(44.dp)
                .offset(y = (-63).dp)
                .wrapContentHeight(),
            contentAlignment = Alignment.TopCenter
        ) {
            Image(painter, contentDescription = null)
            //LottieAnimation(composition, progress = { progress.value })
        }
        if (bottomElement != null) {
            Column(modifier = Modifier.fillMaxWidth().offset(y = (-118).dp)) {
                bottomElement()
            }
        }
    }


}


```

**Comment by alexzhirkevich** [comment] 2024-06-05 12:55
Not all the lottie features have multiplatform support. Are there embedded images in the animation? Can you provide your animation?

**Comment by toffeantyri** [comment] 2024-06-05 14:25
> Not all the lottie features have multiplatform support. Are there embedded images in the animation? Can you provide your animation?

yes, json has embedded images: data:image/png;base64

**Comment by alexzhirkevich** [comment] 2024-06-05 14:44
Then it is duplicate of #1. 
It will be fixed soon with a new renderer. If you want you can clone `standalone` branch and test your animation in the sample app

**Closed as completed by alexzhirkevich** 2024-06-05 14:44 UTC
